const x = {
    _listeners: {},
    _children: [{x
        _listeners: {},
        _children: [{
            _listeners: {},
            _children: [{
                _listeners: {},
                _props: {
                    style: [Circular],
                    onStartShouldSetResponder: [Function: onStartShouldSetResponder],
                    onMoveShouldSetResponder: [Function: onMoveShouldSetResponder],
                    onStartShouldSetResponderCapture: [Function: onStartShouldSetResponderCapture],
                    onMoveShouldSetResponderCapture: [Function: onMoveShouldSetResponderCapture],
                    onResponderGrant: [Function: onResponderGrant],
                    onResponderReject: [Function: onResponderReject],
                    onResponderRelease: [Function: onResponderRelease],
                    onResponderStart: [Function: onResponderStart],
                    onResponderMove: [Function: onResponderMove],
                    onResponderEnd: [Function: onResponderEnd],
                    onResponderTerminate: [Function: onResponderTerminate],
                    onResponderTerminationRequest: [Function: onResponderTerminationRequest],
                    children: {
                        '$$typeof': {},
                        type: {
                            [Function: GLView]
                            defaultProps: {
                                msaaSamples: 4
                            },
                            NativeView: {
                                '$$typeof': {},
                                render: [Object]
                            }
                        },
                        key: null,
                        ref: null,
                        props: {
                            style: {
                                height: 500,
                                width: 500
                            },
                            onContextCreate: {
                                [Function: onContextCreate] toString: [Function]
                            },
                            msaaSamples: 4
                        },
                        _owner: {
                            tag: 0,
                            key: null,
                            elementType: [Function: RNThree],
                            type: [Function: RNThree],
                            stateNode: null,
                            return: {
                                tag: 0,
                                key: null,
                                elementType: [Function: App],
                                type: [Function: App],
                                stateNode: null,
                                return: [Object],
                                child: [Circular],
                                sibling: null,
                                index: 0,
                                ref: null,
                                pendingProps: [Object],
                                memoizedProps: [Object],
                                updateQueue: null,
                                memoizedState: null,
                                dependencies: null,
                                mode: 8,
                                flags: 0,
                                nextEffect: null,
                                firstEffect: [Object],
                                lastEffect: [Object],
                                lanes: 0,
                                childLanes: 0,
                                alternate: [Object],
                                actualDuration: 8.230541666736826,
                                actualStartTime: 472446.12108333345,
                                selfBaseDuration: 0.23558333335677162,
                                treeBaseDuration: 8.694458333193325,
                                _debugID: 23,
                                _debugSource: [Object],
                                _debugOwner: null,
                                _debugNeedsRemount: false,
                                _debugHookTypes: null
                            },
                            child: {
                                tag: 11,
                                key: null,
                                elementType: [Object],
                                type: [Object],
                                stateNode: null,
                                return: [Circular],
                                child: [Object],
                                sibling: null,
                                index: 0,
                                ref: null,
                                pendingProps: [Object],
                                memoizedProps: [Object],
                                updateQueue: null,
                                memoizedState: null,
                                dependencies: null,
                                mode: 8,
                                flags: 1,
                                nextEffect: null,
                                firstEffect: [Object],
                                lastEffect: [Object],
                                lanes: 0,
                                childLanes: 0,
                                alternate: [Object],
                                actualDuration: 5.858208333374932,
                                actualStartTime: 472448.5029166668,
                                selfBaseDuration: 0.03858333331299946,
                                treeBaseDuration: 6.090333333180752,
                                _debugID: 27,
                                _debugSource: [Object],
                                _debugOwner: [Circular],
                                _debugNeedsRemount: false,
                                _debugHookTypes: null
                            },
                            sibling: null,
                            index: 0,
                            ref: null,
                            pendingProps: {},
                            memoizedProps: {},
                            updateQueue: null,
                            memoizedState: {
                                memoizedState: [Object],
                                baseState: null,
                                baseQueue: null,
                                queue: null,
                                next: [Object]
                            },
                            dependencies: null,
                            mode: 8,
                            flags: 1,
                            nextEffect: null,
                            firstEffect: {
                                tag: 5,
                                key: null,
                                elementType: 'RCTSafeAreaView',
                                type: 'RCTSafeAreaView',
                                stateNode: [Object],
                                return: [Object],
                                child: null,
                                sibling: null,
                                index: 0,
                                ref: null,
                                pendingProps: [Object],
                                memoizedProps: [Object],
                                updateQueue: null,
                                memoizedState: null,
                                dependencies: null,
                                mode: 8,
                                flags: 4,
                                nextEffect: null,
                                firstEffect: null,
                                lastEffect: null,
                                lanes: 0,

                                childLanes: 0,
                                alternate: [Object],
                                actualDuration: 0.0407499999855645,
                                actualStartTime: 472448.76958333346,
                                selfBaseDuration: 0.009208333329297602,
                                treeBaseDuration: 0.009208333329297602,
                                _debugID: 36,
                                _debugSource: [Object],
                                _debugOwner: [Object],
                                _debugNeedsRemount: false,
                                _debugHookTypes: null
                            },
                            lastEffect: {
                                tag: 5,
                                key: null,
                                elementType: 'RCTView',
                                type: 'RCTView',
                                stateNode: [Object],
                                return: [Object],
                                child: [Object],
                                sibling: null,
                                index: 0,
                                ref: null,
                                pendingProps: [Object],
                                memoizedProps: [Object],
                                updateQueue: null,
                                memoizedState: null,
                                dependencies: null,
                                mode: 8,
                                flags: 4,
                                nextEffect: null,
                                firstEffect: [Object],
                                lastEffect: [Object],
                                lanes: 0,
                                childLanes: 0,
                                alternate: [Object],
                                actualDuration: 5.7657083334052,
                                actualStartTime: 472448.5962500001,
                                selfBaseDuration: 0.13908333337167278,
                                treeBaseDuration: 6.002208333229646,
                                _debugID: 31,
                                _debugSource: [Object],
                                _debugOwner: [Object],
                                _debugNeedsRemount: false,
                                _debugHookTypes: null
                            },
                            lanes: 0,
                            childLanes: 0,
                            alternate: {
                                tag: 0,
                                key: null,
                                elementType: [Function: RNThree],
                                type: [Function: RNThree],
                                stateNode: null,
                                return: [TOO BIG formatValueCalls 201 exceeded limit of 200],
                                child: [TOO BIG formatValueCalls 202 exceeded limit of 200],
                                sibling: [TOO BIG formatValueCalls 203 exceeded limit of 200],
                                index: [TOO BIG formatValueCalls 204 exceeded limit of 200],
                                ref: [TOO BIG formatValueCalls 205 exceeded limit of 200],
                                pendingProps: [TOO BIG formatValueCalls 206 exceeded limit of 200],
                                memoizedProps: [TOO BIG formatValueCalls 207 exceeded limit of 200],
                                updateQueue: [TOO BIG formatValueCalls 208 exceeded limit of 200],
                                memoizedState: [TOO BIG formatValueCalls 209 exceeded limit of 200],
                                dependencies: [TOO BIG formatValueCalls 210 exceeded limit of 200],
                                mode: [TOO BIG formatValueCalls 211 exceeded limit of 200],
                                flags: [TOO BIG formatValueCalls 212 exceeded limit of 200],
                                nextEffect: [TOO BIG formatValueCalls 213 exceeded limit of 200],
                                firstEffect: [TOO BIG formatValueCalls 214 exceeded limit of 200],
                                lastEffect: [TOO BIG formatValueCalls 215 exceeded limit of 200],
                                lanes: [TOO BIG formatValueCalls 216 exceeded limit of 200],
                                childLanes: [TOO BIG formatValueCalls 217 exceeded limit of 200],
                                alternate: [Circular],
                                actualDuration: [TOO BIG formatValueCalls 218 exceeded limit of 200],
                                actualStartTime: [TOO BIG formatValueCalls 219 exceeded limit of 200],
                                selfBaseDuration: [TOO BIG formatValueCalls 220 exceeded limit of 200],
                                treeBaseDuration: [TOO BIG formatValueCalls 221 exceeded limit of 200],
                                _debugID: [TOO BIG formatValueCalls 222 exceeded limit of 200],
                                _debugSource: [TOO BIG formatValueCalls 223 exceeded limit of 200],
                                _debugOwner: [TOO BIG formatValueCalls 224 exceeded limit of 200],
                                _debugNeedsRemount: [TOO BIG formatValueCalls 225 exceeded limit of 200],
                                _debugHookTypes: [TOO BIG formatValueCalls 226 exceeded limit of 200]
                            },
                            actualDuration: [TOO BIG formatValueCalls 227 exceeded limit of 200],
                            actualStartTime: [TOO BIG formatValueCalls 228 exceeded limit of 200],
                            selfBaseDuration: [TOO BIG formatValueCalls 229 exceeded limit of 200],
                            treeBaseDuration: [TOO BIG formatValueCalls 230 exceeded limit of 200],
                            _debugID: [TOO BIG formatValueCalls 231 exceeded limit of 200],
                            _debugSource: [TOO BIG formatValueCalls 232 exceeded limit of 200],
                            _debugOwner: [TOO BIG formatValueCalls 233 exceeded limit of 200],
                            _debugNeedsRemount: [TOO BIG formatValueCalls 234 exceeded limit of 200],
                            _debugHookTypes: [TOO BIG formatValueCalls 235 exceeded limit of 200]
                        },
                        _store: [TOO BIG formatValueCalls 236 exceeded limit of 200]
                    }
                },
                _callback: [TOO BIG formatValueCalls 237 exceeded limit of 200],
                _animatedView: [TOO BIG formatValueCalls 238 exceeded limit of 200]
            }],
            _style: [TOO BIG formatValueCalls 239 exceeded limit of 200]
        }],
        _transforms: [TOO BIG formatValueCalls 240 exceeded limit of 200]
    }],
    _value: [TOO BIG formatValueCalls 241 exceeded limit of 200],
    _startingValue: [TOO BIG formatValueCalls 242 exceeded limit of 200],
    _offset: [TOO BIG formatValueCalls 243 exceeded limit of 200],
    _animation: [TOO BIG formatValueCalls 244 exceeded limit of 200]
}, {
    _listeners: {},
    _children: [{
        _listeners: {},
        _children: [{
            _listeners: {},
            _children: [{
                _listeners: {},
                _props: {
                    style: [Circular],
                    onStartShouldSetResponder: [Function: onStartShouldSetResponder],
                    onMoveShouldSetResponder: [Function: onMoveShouldSetResponder],
                    onStartShouldSetResponderCapture: [Function: onStartShouldSetResponderCapture],
                    onMoveShouldSetResponderCapture: [Function: onMoveShouldSetResponderCapture],
                    onResponderGrant: [Function: onResponderGrant],
                    onResponderReject: [Function: onResponderReject],
                    onResponderRelease: [Function: onResponderRelease],
                    onResponderStart: [Function: onResponderStart],
                    onResponderMove: [Function: onResponderMove],
                    onResponderEnd: [Function: onResponderEnd],
                    onResponderTerminate: [Function: onResponderTerminate],
                    onResponderTerminationRequest: [Function: onResponderTerminationRequest],
                    children: {
                        '$$typeof': {},
                        type: {
                            [Function: GLView]
                            defaultProps: {
                                msaaSamples: 4
                            },
                            NativeView: {
                                '$$typeof': {},
                                render: [Object]
                            }
                        },
                        key: null,
                        ref: null,
                        props: {
                            style: {
                                height: 500,
                                width: 500
                            },
                            onContextCreate: {
                                [Function: onContextCreate] toString: [Function]
                            },
                            msaaSamples: 4
                        },
                        _owner: {
                            tag: 0,
                            key: null,
                            elementType: [Function: RNThree],
                            type: [Function: RNThree],
                            stateNode: null,
                            return: {
                                tag: 0,
                                key: null,
                                elementType: [Function: App],
                                type: [Function: App],
                                stateNode: null,
                                return: [Object],
                                child: [Circular],
                                sibling: null,
                                index: 0,
                                ref: null,
                                pendingProps: [Object],
                                memoizedProps: [Object],
                                updateQueue: null,
                                memoizedState: null,
                                dependencies: null,
                                mode: 8,
                                flags: 0,
                                nextEffect: null,
                                firstEffect: [Object],
                                lastEffect: [Object],
                                lanes: 0,
                                childLanes: 0,
                                alternate: [Object],
                                actualDuration: 8.230541666736826,
                                actualStartTime: 472446.12108333345,
                                selfBaseDuration: 0.23558333335677162,
                                treeBaseDuration: 8.694458333193325,
                                _debugID: 23,
                                _debugSource: [Object],
                                _debugOwner: null,
                                _debugNeedsRemount: false,
                                _debugHookTypes: null
                            },
                            child: {
                                tag: 11,
                                key: null,
                                elementType: [Object],
                                type: [Object],
                                stateNode: null,
                                return: [Circular],
                                child: [Object],
                                sibling: null,
                                index: 0,
                                ref: null,
                                pendingProps: [Object],
                                memoizedProps: [Object],
                                updateQueue: null,
                                memoizedState: null,
                                dependencies: null,
                                mode: 8,
                                flags: 1,
                                nextEffect: null,
                                firstEffect: [Object],
                                lastEffect: [Object],
                                lanes: 0,
                                childLanes: 0,
                                alternate: [Object],
                                actualDuration: 5.858208333374932,
                                actualStartTime: 472448.5029166668,
                                selfBaseDuration: 0.03858333331299946,
                                treeBaseDuration: 6.090333333180752,
                                _debugID: 27,
                                _debugSource: [Object],
                                _debugOwner: [Circular],
                                _debugNeedsRemount: false,
                                _debugHookTypes: null
                            },
                            sibling: null,
                            index: 0,
                            ref: null,
                            pendingProps: {},
                            memoizedProps: {},
                            updateQueue: null,
                            memoizedState: {
                                memoizedState: [Object],
                                baseState: null,
                                baseQueue: null,
                                queue: null,
                                next: [Object]
                            },
                            dependencies: null,
                            mode: 8,
                            flags: 1,
                            nextEffect: null,
                            firstEffect: {
                                tag: 5,
                                key: null,
                                elementType: 'RCTSafeAreaView',
                                type: 'RCTSafeAreaView',
                                stateNode: [Object],
                                return: [Object],
                                child: null,
                                sibling: null,
                                index: 0,
                                ref: null,
                                pendingProps: [Object],
                                memoizedProps: [Object],
                                updateQueue: null,
                                memoizedState: null,
                                dependencies: null,
                                mode: 8,
                                flags: 4,
                                nextEffect: null,
                                firstEffect: null,
                                lastEffect: null,
                                lanes: 0,
                                childLanes: 0,
                                alternate: [Object],
                                actualDuration: 0.0407499999855645,
                                actualStartTime: 472448.76958333346,
                                selfBaseDuration: 0.009208333329297602,
                                treeBaseDuration: 0.009208333329297602,
                                _debugID: 36,
                                _debugSource: [Object],
                                _debugOwner: [Object],
                                _debugNeedsRemount: false,
                                _debugHookTypes: null
                            },
                            lastEffect: {
                                tag: 5,
                                key: null,
                                elementType: 'RCTView',
                                type: 'RCTView',
                                stateNode: [Object],
                                return: [Object],
                                child: [Object],
                                sibling: null,
                                index: 0,
                                ref: null,
                                pendingProps: [Object],
                                memoizedProps: [Object],
                                updateQueue: null,
                                memoizedState: null,
                                dependencies: null,
                                mode: 8,
                                flags: 4,
                                nextEffect: null,
                                firstEffect: [Object],
                                lastEffect: [Object],
                                lanes: 0,
                                childLanes: 0,
                                alternate: [Object],
                                actualDuration: 5.7657083334052,
                                actualStartTime: 472448.5962500001,
                                selfBaseDuration: 0.13908333337167278,
                                treeBaseDuration: 6.002208333229646,
                                _debugID: 31,
                                _debugSource: [Object],
                                _debugOwner: [Object],
                                _debugNeedsRemount: false,
                                _debugHookTypes: null
                            },
                            lanes: 0,
                            childLanes: 0,
                            alternate: {
                                tag: 0,
                                key: null,
                                elementType: [Function: RNThree],
                                type: [Function: RNThree],
                                stateNode: null,
                                return: [TOO BIG formatValueCalls 201 exceeded limit of 200],
                                child: [TOO BIG formatValueCalls 202 exceeded limit of 200],
                                sibling: [TOO BIG formatValueCalls 203 exceeded limit of 200],
                                index: [TOO BIG formatValueCalls 204 exceeded limit of 200],
                                ref: [TOO BIG formatValueCalls 205 exceeded limit of 200],
                                pendingProps: [TOO BIG formatValueCalls 206 exceeded limit of 200],
                                memoizedProps: [TOO BIG formatValueCalls 207 exceeded limit of 200],
                                updateQueue: [TOO BIG formatValueCalls 208 exceeded limit of 200],
                                memoizedState: [TOO BIG formatValueCalls 209 exceeded limit of 200],
                                dependencies: [TOO BIG formatValueCalls 210 exceeded limit of 200],
                                mode: [TOO BIG formatValueCalls 211 exceeded limit of 200],
                                flags: [TOO BIG formatValueCalls 212 exceeded limit of 200],
                                nextEffect: [TOO BIG formatValueCalls 213 exceeded limit of 200],
                                firstEffect: [TOO BIG formatValueCalls 214 exceeded limit of 200],
                                lastEffect: [TOO BIG formatValueCalls 215 exceeded limit of 200],
                                lanes: [TOO BIG formatValueCalls 216 exceeded limit of 200],
                                childLanes: [TOO BIG formatValueCalls 217 exceeded limit of 200],
                                alternate: [Circular],
                                actualDuration: [TOO BIG formatValueCalls 218 exceeded limit of 200],
                                actualStartTime: [TOO BIG formatValueCalls 219 exceeded limit of 200],
                                selfBaseDuration: [TOO BIG formatValueCalls 220 exceeded limit of 200],
                                treeBaseDuration: [TOO BIG formatValueCalls 221 exceeded limit of 200],
                                _debugID: [TOO BIG formatValueCalls 222 exceeded limit of 200],
                                _debugSource: [TOO BIG formatValueCalls 223 exceeded limit of 200],
                                _debugOwner: [TOO BIG formatValueCalls 224 exceeded limit of 200],
                                _debugNeedsRemount: [TOO BIG formatValueCalls 225 exceeded limit of 200],
                                _debugHookTypes: [TOO BIG formatValueCalls 226 exceeded limit of 200]
                            },
                            actualDuration: [TOO BIG formatValueCalls 227 exceeded limit of 200],
                            actualStartTime: [TOO BIG formatValueCalls 228 exceeded limit of 200],
                            selfBaseDuration: [TOO BIG formatValueCalls 229 exceeded limit of 200],
                            treeBaseDuration: [TOO BIG formatValueCalls 230 exceeded limit of 200],
                            _debugID: [TOO BIG formatValueCalls 231 exceeded limit of 200],
                            _debugSource: [TOO BIG formatValueCalls 232 exceeded limit of 200],
                            _debugOwner: [TOO BIG formatValueCalls 233 exceeded limit of 200],
                            _debugNeedsRemount: [TOO BIG formatValueCalls 234 exceeded limit of 200],
                            _debugHookTypes: [TOO BIG formatValueCalls 235 exceeded limit of 200]
                        },
                        _store: [TOO BIG formatValueCalls 236 exceeded limit of 200]
                    }
                },
                _callback: [TOO BIG formatValueCalls 237 exceeded limit of 200],
                _animatedView: [TOO BIG formatValueCalls 238 exceeded limit of 200]
            }],
            _style: [TOO BIG formatValueCalls 239 exceeded limit of 200]
        }],
        _transforms: [TOO BIG formatValueCalls 240 exceeded limit of 200]
    }],
    _value: [TOO BIG formatValueCalls 241 exceeded limit of 200],
    _startingValue: [TOO BIG formatValueCalls 242 exceeded limit of 200],
    _offset: [TOO BIG formatValueCalls 243 exceeded limit of 200],
    _animation: [TOO BIG formatValueCalls 244 exceeded limit of 200]
}